[package]
name = "rainbow"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
csv = "1.3.1"
fake = { version = "4", features = ["derive", "random_color"] }
teloxide = "0.15.0"
tokio = "1.44.2"
